# Generated by Django 6.0.5 on 2026-09-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatclear'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
